<?xml version="1.0"?>
<!--

  Copyright (c) 2011, PAL Robotics, S.L.
  All rights reserved.

  This work is licensed under the Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported License.
  To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-nd/3.0/ or send a letter to
  Creative Commons, 444 Castro Street, Suite 900, Mountain View, California, 94041, USA.
-->
<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:macro name="stingrayf033c_camera_gazebo_v0" params="name image_format image_topic_name camera_info_topic_name hfov focal_length frame_id hack_baseline image_width image_height">
    <gazebo reference="${name}_frame">

    <sensor:camera name="${name}_sensor">
      <imageFormat>R8G8B8</imageFormat>
      <imageSize>${image_width} ${image_height}</imageSize>
      <hfov>${hfov}</hfov>
      <nearClip>0.1</nearClip>
      <farClip>100</farClip>
      <updateRate>25.0</updateRate>
      <controller:gazebo_ros_prosilica name="${name}_controller" plugin="libgazebo_ros_prosilica.so">
        <alwaysOn>true</alwaysOn>
        <updateRate>25.0</updateRate>
        <cameraName>${name}</cameraName>
        <hackBaseline>${hack_baseline}</hackBaseline>
        <imageTopicName>${image_topic_name}</imageTopicName>
        <cameraInfoTopicName>${camera_info_topic_name}</cameraInfoTopicName>
        <!-- <pollServiceName>request_image</pollServiceName> -->
        <frameName>${frame_id}</frameName>
        <CxPrime>${(image_width+1)/2}</CxPrime>
        <Cx>${(image_width+1)/2}</Cx>
        <Cy>${(image_height+1)/2}</Cy>
        <focalLength>${focal_length}</focalLength> <!-- image_width / (2*tan(hfov_radian /2)) -->
        <distortionK1>0.0</distortionK1>
        <distortionK2>0.0</distortionK2>
        <distortionK3>0.0</distortionK3>
        <distortionT1>0.0</distortionT1>
        <distortionT2>0.0</distortionT2>
      </controller:gazebo_ros_prosilica>
    </sensor:camera>
    <material value="Gazebo/Black" />
    </gazebo>
  </xacro:macro>
</robot>
